name = "arsynox-telegram-bot"
type = "javascript"
account_id = "d8671d3954cd55778a0db1d42961629d"
workers_dev = true
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# These will be set via secrets
BOT_TOKEN = ""
BOT_SECRET = ""
SIA_SECRET = ""
